//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class TB_R_SR_REPORT
    {
        public int Id { get; set; }
        public string SR_NO { get; set; }
        public Nullable<int> TOTAL_SLA { get; set; }
        public Nullable<int> CURRENT_ALERT { get; set; }
        public string CARD_NO { get; set; }
        public string ACCOUNT_NO { get; set; }
        public string CAR_REGIS_NO { get; set; }
        public string CREATOR_BRANCH { get; set; }
        public string CHANNEL_NAME { get; set; }
        public string CALL_ID { get; set; }
        public string ANO { get; set; }
        public string PRODUCTGROUP_NAME { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string CAMPAIGNSERVICE_NAME { get; set; }
        public string TYPE_NAME { get; set; }
        public string AREA_NAME { get; set; }
        public string SUBAREA_NAME { get; set; }
        public string SR_STATUS_NAME { get; set; }
        public Nullable<System.DateTime> CLOSE_DATE { get; set; }
        public string SR_IS_VERIFY_PASS { get; set; }
        public string CREATOR_NAME { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string OWNER_NAME { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE_BY_OWNER { get; set; }
        public string DELEGATOR_NAME { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE_BY_DELEGATE { get; set; }
        public string SR_SUBJECT { get; set; }
        public string SR_REMARK { get; set; }
        public string CONTACT_NAME { get; set; }
        public string CONTACT_SURNAME { get; set; }
        public string RELATIONSHIP { get; set; }
        public string MEDIA_SOURCE_NAME { get; set; }
        public string ATTACH_FILE { get; set; }
        public string JOB_TYPE { get; set; }
        public string CONTACT_NO { get; set; }
        public string PHONE_TYPE_CODE { get; set; }
        public Nullable<int> SR_PAGE_ID { get; set; }
        public Nullable<int> ROLE_ID { get; set; }
        public Nullable<int> OWNER_USER_ID { get; set; }
        public Nullable<int> OWNER_BRANCH_ID { get; set; }
        public Nullable<int> CREATE_USER { get; set; }
        public Nullable<int> CREATE_BRANCH_ID { get; set; }
        public string FIRST_NAME_TH { get; set; }
        public string FIRST_NAME_EN { get; set; }
        public string LAST_NAME_TH { get; set; }
        public string LAST_NAME_EN { get; set; }
        public Nullable<int> PRODUCTGROUP_ID { get; set; }
        public Nullable<int> PRODUCT_ID { get; set; }
        public Nullable<int> CAMPAIGNSERVICE_ID { get; set; }
        public Nullable<int> TYPE_ID { get; set; }
        public Nullable<int> AREA_ID { get; set; }
        public Nullable<int> SUBAREA_ID { get; set; }
        public Nullable<int> SR_STATUS_ID { get; set; }
        public Nullable<int> CHANNEL_ID { get; set; }
        public Nullable<bool> DELETED { get; set; }
    }
}
