//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_C_IGNORE_PRODUCT
    {
        public int PRODUCT_ID { get; set; }
        public string PRODCT_GROUP { get; set; }
        public string PRODUCT { get; set; }
        public string SUBSCRIPTION_CODE { get; set; }
    }
}
