//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_C_ADDRESS_TYPE
    {
        public int ADDRESS_TYPE_ID { get; set; }
        public string ADDRESS_TYPE_CODE { get; set; }
        public string SHORT_DESC_ENG { get; set; }
        public string LONG_DESC_ENG { get; set; }
        public string LONG_DESC_THA { get; set; }
        public string ALLOW_MULTIPLE { get; set; }
        public string CATEGORY_CODE { get; set; }
        public string MAIN_ADDRESS { get; set; }
        public string CIS_CODE { get; set; }
    }
}
