//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_C_AREA_CODE
    {
        public int AREA_CODE_ID { get; set; }
        public string AREA_CODE { get; set; }
        public string SHORT_DESC_ENG { get; set; }
        public string LONG_DESC_ENG { get; set; }
        public string LONG_DESC_THA { get; set; }
    }
}
