//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_ADDRESS_FORMAT
    {
        public int ADDRESS_FORMAT_ID { get; set; }
        public string ADDRESS_FORMAT_CODE { get; set; }
        public string SHORT_DESC_ENG { get; set; }
        public string LONG_DESC_ENG { get; set; }
        public string LONG_DESC_THA { get; set; }
        public string LINE1_LABEL { get; set; }
        public string LINE2_LABEL { get; set; }
        public string LINE3_LABEL { get; set; }
        public string LINE4_LABEL { get; set; }
        public string LINE5_LABEL { get; set; }
        public string LINE6_LABEL { get; set; }
        public string LINE7_LABEL { get; set; }
        public string LINE1_SAMPLE { get; set; }
        public string LINE2_SAMPLE { get; set; }
        public string LINE3_SAMPLE { get; set; }
        public string LINE4_SAMPLE { get; set; }
        public string LINE5_SAMPLE { get; set; }
        public string LINE6_SAMPLE { get; set; }
        public string LINE7_SAMPLE { get; set; }
        public string INVALID_CHAR_SET { get; set; }
        public string FOREIGN_ADDR { get; set; }
    }
}
