//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_ELECTRONIC_ADDRESS
    {
        public int ELECTRONIC_ADDRESS_ID { get; set; }
        public string ELECTRONIC_ADDRESS_CODE { get; set; }
        public string CONTACT_TYPE { get; set; }
        public string SHORT_DESC_ENG { get; set; }
        public string LONG_DESC_ENG { get; set; }
        public string LONG_DESC_THA { get; set; }
        public string ADDRESS_CATEGORY_CODE { get; set; }
        public Nullable<int> MIN_LENGTH { get; set; }
        public Nullable<int> MAX_LENGTH { get; set; }
        public string DISPLAY_LEADING_ZERO { get; set; }
        public string DISPLAY_FORMAT { get; set; }
        public string EXTENSION_SEPERATOR { get; set; }
    }
}
