//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_M_SUBDISTRICT
    {
        public string SubDistrict_Code { get; set; }
        public string SubDistrict_Name { get; set; }
        public string District_Code { get; set; }
    }
}
