//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_T_SR_ACCOUNT
    {
        public int SR_ACCOUNT_ID { get; set; }
        public int SR_ID { get; set; }
        public string PRODUCT_GROUP { get; set; }
        public string PRODUCT { get; set; }
        public string ACCOUNT_NO { get; set; }
        public string BRANCH_NAME { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_DATE { get; set; }
        public Nullable<System.DateTime> EXPIRY_DATE { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string CAR_NO { get; set; }
        public string GRADE { get; set; }
        public Nullable<decimal> KKCIS_ID { get; set; }
        public string PRODUCT_DESC { get; set; }
        public string SUBSCRIPTION_CODE { get; set; }
        public string SUBSCRIPTION_DESC { get; set; }
        public string BRANCH_CODE { get; set; }
        public string ACCOUNT_DESC { get; set; }
    
        public virtual TB_T_SR TB_T_SR { get; set; }
    }
}
