USE CSMDB;   
GO

CREATE INDEX IDX_TB_M_SLA ON TB_M_SLA (PRODUCT_ID, CHANNEL_ID, SR_STATUS_ID, AREA_ID, TYPE_ID, SLA_IS_ACTIVE);
GO

ALTER INDEX IDX_TB_M_SLA ON TB_M_SLA REORGANIZE ;
GO

ALTER INDEX IDX_TB_M_SLA ON TB_M_SLA REBUILD;
GO

--ALTER INDEX ALL ON TB_M_SLA REORGANIZE ;   
--GO

--ALTER INDEX ALL ON TB_M_SLA REBUILD WITH (FILLFACTOR = 80, SORT_IN_TEMPDB = ON, STATISTICS_NORECOMPUTE = ON);
--GO

--for local development
--CREATE UNIQUE INDEX idx_product_id
--ON TB_M_SLA (PRODUCT_ID);

--CREATE INDEX idx_product_id
--ON TB_M_SLA (PRODUCT_ID);

--CREATE INDEX idx_campaignservice_id
--ON TB_M_SLA (CAMPAIGNSERVICE_ID);

--CREATE INDEX idx_area_id
--ON TB_M_SLA (AREA_ID);

--CREATE INDEX idx_subarea_id
--ON TB_M_SLA (SUBAREA_ID);

--CREATE INDEX idx_type_id
--ON TB_M_SLA ([TYPE_ID]);

--CREATE INDEX idx_channel_id
--ON TB_M_SLA (CHANNEL_ID);

--CREATE INDEX idx_sr_status_id
--ON TB_M_SLA (SR_STATUS_ID);