//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_I_CIS_SUBSCRIBE_ADDRESS
    {
        public int CIS_ADDRESS_ID { get; set; }
        public Nullable<int> CUST_ID { get; set; }
        public string CARD_ID { get; set; }
        public string CARD_TYPE_CODE { get; set; }
        public string ADDRESS_TYPE_CODE { get; set; }
        public string ADDRESS_NUMBER { get; set; }
        public string VILLAGE { get; set; }
        public string BUILDING { get; set; }
        public string FLOOR_NO { get; set; }
        public string ROOM_NO { get; set; }
        public string MOO { get; set; }
        public string STREET { get; set; }
        public string SOI { get; set; }
        public string SUB_DISTRICT_CODE { get; set; }
        public string DISTRICT_CODE { get; set; }
        public string PROVICE_CODE { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string POSTAL_CODE { get; set; }
        public string KKCIS_ID { get; set; }
        public string UPDATE_DATE { get; set; }
        public Nullable<int> CUSTOMER_ID { get; set; }
        public string PROD_GROUP { get; set; }
        public string PROD_TYPE { get; set; }
        public string SUBSC_CODE { get; set; }
        public string ERROR { get; set; }
        public string SUB_DISTRICT_VALUE { get; set; }
        public string DISTRICT_VALUE { get; set; }
        public string PROVINCE_VALUE { get; set; }
        public string POSTAL_VALUE { get; set; }
        public string CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public string UPDATED_BY { get; set; }
    }
}
