//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_T_SR_RULE_WORK
    {
        public int RULE_WORK_ID { get; set; }
        public string RULE_WORK_CODE { get; set; }
        public string RULE_WORK_TEMPLATE { get; set; }
        public string RULE_WORK_DESC { get; set; }
    }
}
