//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_C_CUSTOMER_CATEGORY
    {
        public int CUSTOMER_CATEGORY_ID { get; set; }
        public string CUSTOMER_CATEGORY_VALUE { get; set; }
        public string SHORT_DESC_ENG { get; set; }
        public string LONG_DESC_ENG { get; set; }
        public string LONG_DESC_THAI { get; set; }
        public string CUSTOMER_TYPE { get; set; }
    }
}
