//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSM.Data.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_T_SR_CUSTOMER
    {
        public TB_T_SR_CUSTOMER()
        {
            this.TB_T_SR_CUSTOMER_PHONE = new HashSet<TB_T_SR_CUSTOMER_PHONE>();
        }
    
        public int SR_CUSTOMER_ID { get; set; }
        public Nullable<int> SR_ID { get; set; }
        public string SUBSCRIPT_TYPE_NAME { get; set; }
        public string FIRST_NAME_TH { get; set; }
        public string FIRST_NAME_EN { get; set; }
        public string LAST_NAME_TH { get; set; }
        public string LAST_NAME_EN { get; set; }
        public string CARD_NO { get; set; }
        public Nullable<System.DateTime> BIRTH_DATE { get; set; }
        public string EMAIL { get; set; }
        public string TITLE_NAME_TH { get; set; }
        public string TITLE_NAME_EN { get; set; }
        public Nullable<int> EMPLOYEE_ID { get; set; }
        public string FAX { get; set; }
        public Nullable<decimal> KKCIS_ID { get; set; }
        public string CARD_TYPE_CODE { get; set; }
        public Nullable<int> CREATE_USER { get; set; }
        public Nullable<int> UPDATE_USER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    
        public virtual TB_R_USER TB_R_USER { get; set; }
        public virtual TB_R_USER TB_R_USER1 { get; set; }
        public virtual TB_R_USER TB_R_USER2 { get; set; }
        public virtual TB_T_SR TB_T_SR { get; set; }
        public virtual ICollection<TB_T_SR_CUSTOMER_PHONE> TB_T_SR_CUSTOMER_PHONE { get; set; }
    }
}
